name: Build Mac OS X app

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        architecture: [x64]
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      run: |
        curl https://www.python.org/ftp/python/3.8.6/python-3.8.6-macosx10.9.pkg --output pythonInstaller.pkg
        sudo installer -pkg pythonInstaller.pkg -target /
        python3 --version
        python3 -c "import platform; print('macOS version:', platform.mac_ver()[0])"
    - name: Setup venv
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python --version
        python -c "import sys; print('\n'.join(sys.path))"
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip pyinstaller setuptools wheel cython cffi -r requirements.txt
    - name: Build Cython ext
      run: |
        source venv/bin/activate
        python setup.py build_ext --inplace
    - name: Make pyinstaller spec
      run: |
        source venv/bin/activate
        pyi-makespec --hidden-import="pkg_resources.py2_warn" -F --add-data images/\*:images --add-data \*.png:. --add-data \*.ico:. -w -i P-face.icns pronterface.py
    - name: Make pyinstaller build
      run: |
        source venv/bin/activate
        pyinstaller  --windowed --clean pronterface.spec -y
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v2
      with:
        name: macosapp_${{ matrix.os }}_${{ matrix.architecture }}_${{ matrix.python-version }}
        path: dist/*
